"""initial authentication schema

Revision ID: f102fc8ed43d
Revises:
Create Date: 2026-07-21 16:21:55.997376

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f102fc8ed43d"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "server_sessions",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("session_id", sa.String(length=255), nullable=True),
        sa.Column("data", sa.LargeBinary(), nullable=True),
        sa.Column("expiry", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("session_id"),
        if_not_exists=True,
    )
    op.create_table(
        "roles",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=32), nullable=False),
        sa.Column("description", sa.String(length=255), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("name"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("first_name", sa.String(length=100), nullable=False),
        sa.Column("last_name", sa.String(length=100), nullable=False),
        sa.Column("login", sa.String(length=100), nullable=False),
        sa.Column("login_normalized", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=512), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("failed_login_count", sa.Integer(), nullable=False),
        sa.Column("locked_until", sa.DateTime(timezone=True), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.CheckConstraint("failed_login_count >= 0", name="ck_users_failed_count"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(
            "ix_users_active_locked", ["is_active", "locked_until"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_users_login_normalized"), ["login_normalized"], unique=True
        )

    op.create_table(
        "authentication_attempts",
        sa.Column("id", sa.Uuid(), nullable=False),
        sa.Column("user_id", sa.Uuid(), nullable=True),
        sa.Column("attempted_login", sa.String(length=100), nullable=False),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.Column("internal_failure_reason", sa.String(length=32), nullable=False),
        sa.Column("ip_address_hash", sa.String(length=64), nullable=True),
        sa.Column("user_agent", sa.String(length=255), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("authentication_attempts", schema=None) as batch_op:
        batch_op.create_index(
            "ix_auth_attempt_success_created", ["success", "created_at"], unique=False
        )
        batch_op.create_index(
            "ix_auth_attempt_user_created", ["user_id", "created_at"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_authentication_attempts_created_at"),
            ["created_at"],
            unique=False,
        )

    op.create_table(
        "user_roles",
        sa.Column("user_id", sa.Uuid(), nullable=False),
        sa.Column("role_id", sa.Integer(), nullable=False),
        sa.Column("assigned_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["role_id"], ["roles.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("user_id", "role_id"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("user_roles")
    with op.batch_alter_table("authentication_attempts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_authentication_attempts_created_at"))
        batch_op.drop_index("ix_auth_attempt_user_created")
        batch_op.drop_index("ix_auth_attempt_success_created")

    op.drop_table("authentication_attempts")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_login_normalized"))
        batch_op.drop_index("ix_users_active_locked")

    op.drop_table("users")
    op.drop_table("roles")
    op.drop_table("server_sessions", if_exists=True)
    # ### end Alembic commands ###
